require 'rake'
require 'rake/testtask'
require 'rake/clean'

begin
	require 'jeweler'
	Jeweler::Tasks.new do |gemspec|
		gemspec.name = "msgpack-idl"
		gemspec.summary = "MessagePack IDL Processor"
		gemspec.author = "FURUHASHI Sadayuki"
		gemspec.email = "frsyuki@users.sourceforge.jp"
		gemspec.homepage = "http://msgpack.org/"
		gemspec.rubyforge_project = "msgpack"
		gemspec.has_rdoc = true
		gemspec.add_dependency "parslet", ">= 0.2.0"
		gemspec.require_paths = ["lib"]
		gemspec.test_files = Dir["test/test_*.rb"]
		gemspec.files = Dir["lib/**/*", "ext/**/*", "test/**/*", "spec/**/*", "tasks/**/*"] + %w[AUTHORS ChangeLog README]
		gemspec.add_development_dependency('rspec')
	end
	Jeweler::GemcutterTasks.new
rescue LoadError
	puts "Jeweler not available. Install it with: gem install jeweler"
end

VERSION_FILE = "lib/msgpack/idl/version.rb"

file VERSION_FILE => ["VERSION"] do |t|
	version = File.read("VERSION").strip
	File.open(VERSION_FILE, "w") {|f|
		f.write <<EOF
module MessagePack
module RPC
module IDL

VERSION = '#{version}'

end
end
end
EOF
	}
end

task :default => [VERSION_FILE, :build]

#task :test => ['test:unit','spec:unit']
#load 'tasks/msgpack_idl_tasks.rake'
